import {
  ChangeEvent,
  PointerEvent as ReactPointerEvent,
  WheelEvent,
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState
} from "react";
import type {
  MansionPsdManifest,
  MansionRectangle,
  MansionRegion,
  MansionRegionFile,
  MansionRegionKind,
  NormalizedRectangle,
  NormalizedPoint
} from "./types";
import { cloneDefaultMansionRegions } from "./defaultRegions";

const STORAGE_KEY = "abyssa:mansion-map-regions:v2:floor-aligned-v1";
const MIN_SCALE = 0.08;
const MAX_SCALE = 4;
const REGION_COLORS: Record<MansionRegionKind, string> = {
  room: "#e8ba67",
  building: "#73c9d1",
  trace: "#d58aca",
  other: "#a9bd8d"
};

interface ViewTransform {
  x: number;
  y: number;
  scale: number;
}

interface DraftRegion {
  id: string;
  label: string;
  kind: MansionRegionKind;
  points: NormalizedPoint[];
}

interface DraftRectangle {
  id: string;
  label: string;
  kind: MansionRegionKind;
}

interface RectangleDrawSession {
  pointerId: number;
  start: NormalizedPoint;
}

interface PanSession {
  pointerId: number;
  startClientX: number;
  startClientY: number;
  startX: number;
  startY: number;
}

function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

function roundCoordinate(value: number) {
  return Number(clamp(value, 0, 1).toFixed(6));
}

function rectangleFromPoints(start: NormalizedPoint, end: NormalizedPoint): NormalizedRectangle {
  return {
    x: roundCoordinate(Math.min(start.x, end.x)),
    y: roundCoordinate(Math.min(start.y, end.y)),
    width: roundCoordinate(Math.abs(end.x - start.x)),
    height: roundCoordinate(Math.abs(end.y - start.y))
  };
}

function cleanId(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9_-]/g, "");
}

function readSavedFile(): Pick<MansionRegionFile, "regions" | "rectangles"> {
  try {
    const value = window.localStorage.getItem(STORAGE_KEY);
    if (!value) return cloneDefaultMansionRegions();
    const parsed = JSON.parse(value) as MansionRegionFile;
    return {
      regions: Array.isArray(parsed.regions) ? parsed.regions : [],
      rectangles: Array.isArray(parsed.rectangles) ? parsed.rectangles : []
    };
  } catch {
    return cloneDefaultMansionRegions();
  }
}

function makeRegionFile(
  manifest: MansionPsdManifest,
  regions: MansionRegion[],
  rectangles: MansionRectangle[]
): MansionRegionFile {
  return {
    version: 2,
    canvas: { width: manifest.width, height: manifest.height },
    rectangles: rectangles.map((rectangle) => ({
      ...rectangle,
      rect: {
        x: roundCoordinate(rectangle.rect.x),
        y: roundCoordinate(rectangle.rect.y),
        width: roundCoordinate(rectangle.rect.width),
        height: roundCoordinate(rectangle.rect.height)
      }
    })),
    regions: regions.map((region) => ({
      ...region,
      points: region.points.map((point) => ({
        x: roundCoordinate(point.x),
        y: roundCoordinate(point.y)
      }))
    }))
  };
}

function createTypeScript(file: MansionRegionFile) {
  return `// Generated by the Abyssa mansion region editor.\n` +
    `export const MANSION_CANVAS = ${JSON.stringify(file.canvas, null, 2)} as const;\n\n` +
    `export const MANSION_RECTANGLES = ${JSON.stringify(file.rectangles, null, 2)} as const;\n\n` +
    `export const MANSION_REGIONS = ${JSON.stringify(file.regions, null, 2)} as const;\n`;
}

function downloadText(filename: string, content: string, type: string) {
  const url = URL.createObjectURL(new Blob([content], { type }));
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

function isEditableTarget(target: EventTarget | null) {
  return target instanceof HTMLInputElement ||
    target instanceof HTMLTextAreaElement ||
    target instanceof HTMLSelectElement;
}

export function MansionRegionEditor() {
  const viewportRef = useRef<HTMLDivElement>(null);
  const panRef = useRef<PanSession | null>(null);
  const rectangleDrawRef = useRef<RectangleDrawSession | null>(null);
  const fitInitializedRef = useRef(false);
  const spacePressedRef = useRef(false);
  const [savedFile] = useState(readSavedFile);
  const [manifest, setManifest] = useState<MansionPsdManifest | null>(null);
  const [manifestError, setManifestError] = useState("");
  const [enabledLayers, setEnabledLayers] = useState<Set<string>>(new Set());
  const [regions, setRegions] = useState<MansionRegion[]>(savedFile.regions);
  const [rectangles, setRectangles] = useState<MansionRectangle[]>(savedFile.rectangles);
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [selectedRectangleId, setSelectedRectangleId] = useState<string | null>(null);
  const [draft, setDraft] = useState<DraftRegion | null>(null);
  const [rectangleDraft, setRectangleDraft] = useState<DraftRectangle | null>(null);
  const [rectanglePreview, setRectanglePreview] = useState<NormalizedRectangle | null>(null);
  const [view, setView] = useState<ViewTransform>({ x: 0, y: 0, scale: 0.2 });
  const [status, setStatus] = useState("等待框选");

  useEffect(() => {
    const manifestUrl = `${import.meta.env.BASE_URL}mansion-map/manifest.json`;
    fetch(manifestUrl)
      .then((response) => {
        if (!response.ok) throw new Error(`${response.status}`);
        return response.json() as Promise<MansionPsdManifest>;
      })
      .then((value) => {
        setManifest(value);
        setEnabledLayers(new Set(value.layers.filter((layer) => layer.visible).map((layer) => layer.id)));
      })
      .catch(() => setManifestError("无法读取 PSD 图层清单，请先运行解包脚本。"));
  }, []);

  useEffect(() => {
    if (!manifest) return;
    window.localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify(makeRegionFile(manifest, regions, rectangles))
    );
  }, [manifest, rectangles, regions]);

  const fitToView = useCallback(() => {
    if (!manifest || !viewportRef.current) return;
    const { clientWidth, clientHeight } = viewportRef.current;
    const scale = Math.min(
      (clientWidth - 48) / manifest.width,
      (clientHeight - 48) / manifest.height
    );
    setView({
      scale,
      x: (clientWidth - manifest.width * scale) / 2,
      y: (clientHeight - manifest.height * scale) / 2
    });
  }, [manifest]);

  useEffect(() => {
    if (!manifest || !viewportRef.current) return;
    if (!fitInitializedRef.current) {
      fitInitializedRef.current = true;
      fitToView();
    }
    const observer = new ResizeObserver(() => fitToView());
    observer.observe(viewportRef.current);
    return () => observer.disconnect();
  }, [fitToView, manifest]);

  const clientToNormalized = useCallback((clientX: number, clientY: number) => {
    if (!manifest || !viewportRef.current) return null;
    const rect = viewportRef.current.getBoundingClientRect();
    return {
      x: roundCoordinate((clientX - rect.left - view.x) / view.scale / manifest.width),
      y: roundCoordinate((clientY - rect.top - view.y) / view.scale / manifest.height)
    };
  }, [manifest, view]);

  const uniqueRegionId = useCallback((candidate: string) => {
    const allIds = [...regions.map((region) => region.id), ...rectangles.map((rectangle) => rectangle.id)];
    const base = cleanId(candidate) || `region-${allIds.length + 1}`;
    if (!allIds.includes(base)) return base;
    let suffix = 2;
    while (allIds.includes(`${base}-${suffix}`)) suffix += 1;
    return `${base}-${suffix}`;
  }, [rectangles, regions]);

  const beginRegion = () => {
    const index = regions.length + rectangles.length + 1;
    setSelectedId(null);
    setSelectedRectangleId(null);
    setRectangleDraft(null);
    setRectanglePreview(null);
    setDraft({
      id: uniqueRegionId(`region-${index}`),
      label: `未命名区域 ${index}`,
      kind: "room",
      points: []
    });
    setStatus("框选中：逐点点击，按 Enter 或点击首点闭合");
  };

  const beginRectangle = () => {
    const index = regions.length + rectangles.length + 1;
    setSelectedId(null);
    setSelectedRectangleId(null);
    setDraft(null);
    setRectanglePreview(null);
    setRectangleDraft({
      id: uniqueRegionId(`rectangle-${index}`),
      label: `未命名矩形 ${index}`,
      kind: "room"
    });
    setStatus("矩形框选中：在画面上按住并拖拽");
  };

  const completeDraft = useCallback(() => {
    if (!draft || draft.points.length < 3) {
      setStatus("至少需要 3 个顶点");
      return;
    }
    const region: MansionRegion = {
      ...draft,
      id: uniqueRegionId(draft.id),
      points: draft.points.map((point) => ({ ...point }))
    };
    setRegions((current) => [...current, region]);
    setSelectedId(region.id);
    setDraft(null);
    setStatus(`已保存：${region.label}`);
  }, [draft, uniqueRegionId]);

  useEffect(() => {
    const onKeyDown = (event: KeyboardEvent) => {
      if (event.code === "Space" && !isEditableTarget(event.target)) {
        spacePressedRef.current = true;
        event.preventDefault();
      }
      if ((!draft && !rectangleDraft) || isEditableTarget(event.target)) return;
      if (event.key === "Escape") {
        setDraft(null);
        setRectangleDraft(null);
        setRectanglePreview(null);
        rectangleDrawRef.current = null;
        setStatus("已取消本次框选");
        return;
      }
      if (!draft) return;
      if (event.key === "Enter") {
        event.preventDefault();
        completeDraft();
      } else if (event.key === "Backspace") {
        event.preventDefault();
        setDraft((current) => current ? { ...current, points: current.points.slice(0, -1) } : null);
      }
    };
    const onKeyUp = (event: KeyboardEvent) => {
      if (event.code === "Space") spacePressedRef.current = false;
    };
    window.addEventListener("keydown", onKeyDown);
    window.addEventListener("keyup", onKeyUp);
    return () => {
      window.removeEventListener("keydown", onKeyDown);
      window.removeEventListener("keyup", onKeyUp);
    };
  }, [completeDraft, draft, rectangleDraft]);

  const handleViewportPointerDown = (event: ReactPointerEvent<HTMLDivElement>) => {
    const wantsPan = event.button === 1 || spacePressedRef.current;
    if (wantsPan) {
      event.preventDefault();
      panRef.current = {
        pointerId: event.pointerId,
        startClientX: event.clientX,
        startClientY: event.clientY,
        startX: view.x,
        startY: view.y
      };
      event.currentTarget.setPointerCapture(event.pointerId);
      return;
    }
    if (event.button !== 0) return;
    const point = clientToNormalized(event.clientX, event.clientY);
    if (!point) return;
    if (rectangleDraft) {
      rectangleDrawRef.current = { pointerId: event.pointerId, start: point };
      setRectanglePreview({ x: point.x, y: point.y, width: 0, height: 0 });
      event.currentTarget.setPointerCapture(event.pointerId);
      return;
    }
    if (!draft) return;
    setDraft((current) => current ? { ...current, points: [...current.points, point] } : null);
  };

  const handleViewportPointerMove = (event: ReactPointerEvent<HTMLDivElement>) => {
    const pan = panRef.current;
    if (pan?.pointerId === event.pointerId) {
      setView((current) => ({
        ...current,
        x: pan.startX + event.clientX - pan.startClientX,
        y: pan.startY + event.clientY - pan.startClientY
      }));
      return;
    }
    const rectangleDraw = rectangleDrawRef.current;
    if (rectangleDraw?.pointerId === event.pointerId) {
      const point = clientToNormalized(event.clientX, event.clientY);
      if (point) setRectanglePreview(rectangleFromPoints(rectangleDraw.start, point));
    }
  };

  const finishPan = (event: ReactPointerEvent<HTMLDivElement>) => {
    if (panRef.current?.pointerId === event.pointerId) panRef.current = null;
    const rectangleDraw = rectangleDrawRef.current;
    if (rectangleDraw?.pointerId !== event.pointerId) return;
    rectangleDrawRef.current = null;
    const end = clientToNormalized(event.clientX, event.clientY);
    if (!end || !rectangleDraft) return;
    const rect = rectangleFromPoints(rectangleDraw.start, end);
    if (rect.width < 0.001 || rect.height < 0.001) {
      setRectanglePreview(null);
      setStatus("矩形太小，请重新拖拽");
      return;
    }
    const rectangle: MansionRectangle = {
      ...rectangleDraft,
      id: uniqueRegionId(rectangleDraft.id),
      rect
    };
    setRectangles((current) => [...current, rectangle]);
    setSelectedRectangleId(rectangle.id);
    setRectangleDraft(null);
    setRectanglePreview(null);
    setStatus(`已保存矩形：${rectangle.label}`);
  };

  const handleWheel = (event: WheelEvent<HTMLDivElement>) => {
    if (!manifest || !viewportRef.current) return;
    event.preventDefault();
    const rect = viewportRef.current.getBoundingClientRect();
    const localX = event.clientX - rect.left;
    const localY = event.clientY - rect.top;
    const canvasX = (localX - view.x) / view.scale;
    const canvasY = (localY - view.y) / view.scale;
    const nextScale = clamp(view.scale * Math.exp(-event.deltaY * 0.0015), MIN_SCALE, MAX_SCALE);
    setView({
      scale: nextScale,
      x: localX - canvasX * nextScale,
      y: localY - canvasY * nextScale
    });
  };

  const updateRegion = (id: string, patch: Partial<MansionRegion>) => {
    setRegions((current) => current.map((region) => region.id === id ? { ...region, ...patch } : region));
  };

  const renameRegion = (oldId: string, candidate: string) => {
    const nextId = cleanId(candidate);
    if (!nextId || nextId === oldId) return;
    if ([...regions, ...rectangles].some((region) => region.id === nextId && region.id !== oldId)) {
      setStatus(`参数 ID “${nextId}” 已存在`);
      return;
    }
    setRegions((current) => current.map((region) =>
      region.id === oldId ? { ...region, id: nextId } : region
    ));
    setSelectedId(nextId);
  };

  const updateRectangle = (id: string, patch: Partial<MansionRectangle>) => {
    setRectangles((current) => current.map((rectangle) =>
      rectangle.id === id ? { ...rectangle, ...patch } : rectangle
    ));
  };

  const renameRectangle = (oldId: string, candidate: string) => {
    const nextId = cleanId(candidate);
    if (!nextId || nextId === oldId) return;
    if ([...regions, ...rectangles].some((region) => region.id === nextId && region.id !== oldId)) {
      setStatus(`参数 ID “${nextId}” 已存在`);
      return;
    }
    setRectangles((current) => current.map((rectangle) =>
      rectangle.id === oldId ? { ...rectangle, id: nextId } : rectangle
    ));
    setSelectedRectangleId(nextId);
  };

  const moveVertex = (
    event: ReactPointerEvent<SVGCircleElement>,
    regionId: string,
    pointIndex: number
  ) => {
    const point = clientToNormalized(event.clientX, event.clientY);
    if (!point) return;
    setRegions((current) => current.map((region) => {
      if (region.id !== regionId) return region;
      const points = region.points.map((item, index) => index === pointIndex ? point : item);
      return { ...region, points };
    }));
  };

  const moveRectangleCorner = (
    event: ReactPointerEvent<SVGCircleElement>,
    rectangleId: string,
    corner: "tl" | "tr" | "br" | "bl"
  ) => {
    const point = clientToNormalized(event.clientX, event.clientY);
    if (!point) return;
    setRectangles((current) => current.map((rectangle) => {
      if (rectangle.id !== rectangleId) return rectangle;
      const { x, y, width, height } = rectangle.rect;
      const opposite = {
        tl: { x: x + width, y: y + height },
        tr: { x, y: y + height },
        br: { x, y },
        bl: { x: x + width, y }
      }[corner];
      return { ...rectangle, rect: rectangleFromPoints(opposite, point) };
    }));
  };

  const exportFile = useMemo(
    () => manifest ? makeRegionFile(manifest, regions, rectangles) : null,
    [manifest, rectangles, regions]
  );
  const selectedRegion = regions.find((region) => region.id === selectedId) ?? null;
  const selectedRectangle = rectangles.find((rectangle) => rectangle.id === selectedRectangleId) ?? null;

  const handleImport = async (event: ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    event.target.value = "";
    if (!file || !manifest) return;
    try {
      const parsed = JSON.parse(await file.text()) as MansionRegionFile;
      if (parsed.version !== 2 || !Array.isArray(parsed.regions) || !Array.isArray(parsed.rectangles)) throw new Error();
      if (parsed.canvas.width !== manifest.width || parsed.canvas.height !== manifest.height) {
        throw new Error("画布尺寸不一致");
      }
      setRegions(parsed.regions);
      setRectangles(parsed.rectangles);
      setSelectedId(null);
      setSelectedRectangleId(null);
      setDraft(null);
      setRectangleDraft(null);
      setRectanglePreview(null);
      setStatus(`已导入 ${parsed.rectangles.length} 个矩形、${parsed.regions.length} 个多边形`);
    } catch (error) {
      setStatus(error instanceof Error && error.message ? error.message : "导入文件格式无效");
    }
  };

  const restoreDefaults = () => {
    if (!window.confirm("恢复 v8 原稿默认标注？当前浏览器中的微调会被替换。")) return;
    const defaults = cloneDefaultMansionRegions();
    setRectangles(defaults.rectangles);
    setRegions(defaults.regions);
    setSelectedId(null);
    setSelectedRectangleId(null);
    setDraft(null);
    setRectangleDraft(null);
    setRectanglePreview(null);
    setStatus(`已恢复 ${defaults.rectangles.length} 个矩形、${defaults.regions.length} 个多边形`);
  };

  if (manifestError) {
    return <main className="mansion-editor mansion-editor--error">{manifestError}</main>;
  }
  if (!manifest) {
    return <main className="mansion-editor mansion-editor--loading">正在读取 PSD 图层…</main>;
  }

  return (
    <main className="mansion-editor">
      <header className="mansion-editor__topbar">
        <div>
          <strong>洋馆热区标注器</strong>
          <span>{manifest.source} · {manifest.width} × {manifest.height}</span>
        </div>
        <div className="mansion-editor__view-actions">
          <button type="button" onClick={fitToView}>适配窗口</button>
          <button
            type="button"
            onClick={() => setView({ x: 24, y: 24, scale: 1 })}
          >100%</button>
          <output>{Math.round(view.scale * 100)}%</output>
        </div>
      </header>

      <section className="mansion-editor__workspace">
        <div
          ref={viewportRef}
          className={`mansion-editor__viewport ${draft || rectangleDraft ? "is-drawing" : ""}`}
          onPointerDown={handleViewportPointerDown}
          onPointerMove={handleViewportPointerMove}
          onPointerUp={finishPan}
          onPointerCancel={finishPan}
          onWheel={handleWheel}
        >
          <div
            className="mansion-editor__canvas"
            style={{
              width: manifest.width,
              height: manifest.height,
              transform: `translate(${view.x}px, ${view.y}px) scale(${view.scale})`
            }}
          >
            {manifest.layers.map((layer) => enabledLayers.has(layer.id) && (
              <img
                key={layer.id}
                className="mansion-editor__layer"
                src={`${import.meta.env.BASE_URL}mansion-map/${layer.src}`}
                alt=""
                draggable={false}
                style={{
                  left: layer.x,
                  top: layer.y,
                  width: layer.width,
                  height: layer.height,
                  opacity: layer.opacity,
                  zIndex: layer.order
                }}
              />
            ))}

            <svg
              className="mansion-editor__regions"
              viewBox={`0 0 ${manifest.width} ${manifest.height}`}
              aria-label="洋馆区域标注"
            >
              {rectangles.map((rectangle) => {
                const color = REGION_COLORS[rectangle.kind];
                const x = rectangle.rect.x * manifest.width;
                const y = rectangle.rect.y * manifest.height;
                const width = rectangle.rect.width * manifest.width;
                const height = rectangle.rect.height * manifest.height;
                const selected = rectangle.id === selectedRectangleId;
                const corners = [
                  ["tl", x, y],
                  ["tr", x + width, y],
                  ["br", x + width, y + height],
                  ["bl", x, y + height]
                ] as const;
                return (
                  <g key={rectangle.id}>
                    <rect
                      x={x}
                      y={y}
                      width={width}
                      height={height}
                      fill={color}
                      fillOpacity={selected ? 0.28 : 0.14}
                      stroke={color}
                      strokeWidth={selected ? 4 : 2}
                      vectorEffect="non-scaling-stroke"
                      onPointerDown={(event) => {
                        if (draft || rectangleDraft) return;
                        event.stopPropagation();
                        setSelectedRectangleId(rectangle.id);
                        setSelectedId(null);
                      }}
                    />
                    {selected && corners.map(([corner, cx, cy]) => (
                      <circle
                        key={`${rectangle.id}-${corner}`}
                        cx={cx}
                        cy={cy}
                        r={8 / view.scale}
                        fill="#fff8e8"
                        stroke={color}
                        strokeWidth={3 / view.scale}
                        onPointerDown={(event) => {
                          event.stopPropagation();
                          event.currentTarget.setPointerCapture(event.pointerId);
                        }}
                        onPointerMove={(event) => {
                          if (event.currentTarget.hasPointerCapture(event.pointerId)) {
                            moveRectangleCorner(event, rectangle.id, corner);
                          }
                        }}
                      />
                    ))}
                  </g>
                );
              })}

              {regions.map((region) => {
                const color = REGION_COLORS[region.kind];
                const points = region.points
                  .map((point) => `${point.x * manifest.width},${point.y * manifest.height}`)
                  .join(" ");
                const selected = region.id === selectedId;
                return (
                  <g key={region.id}>
                    <polygon
                      points={points}
                      fill={color}
                      fillOpacity={selected ? 0.28 : 0.14}
                      stroke={color}
                      strokeWidth={selected ? 4 : 2}
                      vectorEffect="non-scaling-stroke"
                      onPointerDown={(event) => {
                        if (draft || rectangleDraft) return;
                        event.stopPropagation();
                        setSelectedId(region.id);
                        setSelectedRectangleId(null);
                      }}
                    />
                    {selected && region.points.map((point, index) => (
                      <circle
                        key={`${region.id}-${index}`}
                        cx={point.x * manifest.width}
                        cy={point.y * manifest.height}
                        r={8 / view.scale}
                        fill="#fff8e8"
                        stroke={color}
                        strokeWidth={3 / view.scale}
                        onPointerDown={(event) => {
                          event.stopPropagation();
                          event.currentTarget.setPointerCapture(event.pointerId);
                        }}
                        onPointerMove={(event) => {
                          if (event.currentTarget.hasPointerCapture(event.pointerId)) {
                            moveVertex(event, region.id, index);
                          }
                        }}
                      />
                    ))}
                  </g>
                );
              })}

              {rectangleDraft && rectanglePreview && (
                <rect
                  x={rectanglePreview.x * manifest.width}
                  y={rectanglePreview.y * manifest.height}
                  width={rectanglePreview.width * manifest.width}
                  height={rectanglePreview.height * manifest.height}
                  fill={REGION_COLORS[rectangleDraft.kind]}
                  fillOpacity={0.22}
                  stroke={REGION_COLORS[rectangleDraft.kind]}
                  strokeWidth={3}
                  strokeDasharray="10 7"
                  vectorEffect="non-scaling-stroke"
                />
              )}

              {draft && draft.points.length > 0 && (
                <g>
                  <polyline
                    points={draft.points
                      .map((point) => `${point.x * manifest.width},${point.y * manifest.height}`)
                      .join(" ")}
                    fill={draft.points.length >= 3 ? REGION_COLORS[draft.kind] : "none"}
                    fillOpacity={0.18}
                    stroke={REGION_COLORS[draft.kind]}
                    strokeWidth={3}
                    vectorEffect="non-scaling-stroke"
                  />
                  {draft.points.map((point, index) => (
                    <circle
                      key={index}
                      cx={point.x * manifest.width}
                      cy={point.y * manifest.height}
                      r={(index === 0 ? 11 : 6) / view.scale}
                      fill={index === 0 ? "#fff3bd" : REGION_COLORS[draft.kind]}
                      stroke="#201a16"
                      strokeWidth={2 / view.scale}
                      onPointerDown={index === 0 ? (event) => {
                        event.stopPropagation();
                        completeDraft();
                      } : undefined}
                    />
                  ))}
                </g>
              )}
            </svg>
          </div>

          <div className="mansion-editor__hint">
            矩形：按住拖拽 · 多边形：逐点点击 · 空格/中键移动画布 · Esc 取消
          </div>
        </div>

        <aside className="mansion-editor__sidebar">
          <section>
            <div className="mansion-editor__section-title">
              <h2>矩形区域</h2>
              <button type="button" className="is-primary" onClick={beginRectangle}>
                + 新建矩形
              </button>
            </div>

            {(rectangleDraft || selectedRectangle) && (
              <div className="mansion-editor__fields">
                <label>
                  参数 ID
                  <input
                    value={(rectangleDraft ?? selectedRectangle)!.id}
                    onChange={(event) => rectangleDraft
                      ? setRectangleDraft({ ...rectangleDraft, id: event.target.value })
                      : renameRectangle(selectedRectangle!.id, event.target.value)}
                  />
                </label>
                <label>
                  显示名称
                  <input
                    value={(rectangleDraft ?? selectedRectangle)!.label}
                    onChange={(event) => rectangleDraft
                      ? setRectangleDraft({ ...rectangleDraft, label: event.target.value })
                      : updateRectangle(selectedRectangle!.id, { label: event.target.value })}
                  />
                </label>
                <label>
                  类型
                  <select
                    value={(rectangleDraft ?? selectedRectangle)!.kind}
                    onChange={(event) => {
                      const kind = event.target.value as MansionRegionKind;
                      rectangleDraft
                        ? setRectangleDraft({ ...rectangleDraft, kind })
                        : updateRectangle(selectedRectangle!.id, { kind });
                    }}
                  >
                    <option value="room">房间</option>
                    <option value="building">功能建筑</option>
                    <option value="trace">生活痕迹</option>
                    <option value="other">其他</option>
                  </select>
                </label>
                {rectangleDraft ? (
                  <div className="mansion-editor__draft-note">
                    在画面上按住鼠标并拖出矩形；Esc 取消。
                  </div>
                ) : (
                  <button
                    type="button"
                    className="is-danger"
                    onClick={() => {
                      setRectangles((current) => current.filter((rectangle) => rectangle.id !== selectedRectangle!.id));
                      setSelectedRectangleId(null);
                      setStatus("矩形已删除");
                    }}
                  >删除当前矩形</button>
                )}
              </div>
            )}

            <div className="mansion-editor__region-list">
              {rectangles.length === 0 && <p>适合大多数房间：点击“新建矩形”，然后在画面上拖拽。</p>}
              {rectangles.map((rectangle) => (
                <button
                  type="button"
                  key={rectangle.id}
                  className={rectangle.id === selectedRectangleId ? "is-selected" : ""}
                  onClick={() => {
                    setSelectedRectangleId(rectangle.id);
                    setSelectedId(null);
                    setDraft(null);
                    setRectangleDraft(null);
                    setRectanglePreview(null);
                  }}
                >
                  <i style={{ background: REGION_COLORS[rectangle.kind] }} />
                  <span>{rectangle.label}<small>{rectangle.id} · 矩形</small></span>
                </button>
              ))}
            </div>
          </section>

          <section>
            <div className="mansion-editor__section-title">
              <h2>多边形区域</h2>
              <button type="button" className="is-primary" onClick={beginRegion}>
                + 新建多边形
              </button>
            </div>

            {(draft || selectedRegion) && (
              <div className="mansion-editor__fields">
                <label>
                  参数 ID
                  <input
                    value={(draft ?? selectedRegion)!.id}
                    onChange={(event) => draft
                      ? setDraft({ ...draft, id: event.target.value })
                      : renameRegion(selectedRegion!.id, event.target.value)}
                  />
                </label>
                <label>
                  显示名称
                  <input
                    value={(draft ?? selectedRegion)!.label}
                    onChange={(event) => draft
                      ? setDraft({ ...draft, label: event.target.value })
                      : updateRegion(selectedRegion!.id, { label: event.target.value })}
                  />
                </label>
                <label>
                  类型
                  <select
                    value={(draft ?? selectedRegion)!.kind}
                    onChange={(event) => {
                      const kind = event.target.value as MansionRegionKind;
                      draft
                        ? setDraft({ ...draft, kind })
                        : updateRegion(selectedRegion!.id, { kind });
                    }}
                  >
                    <option value="room">房间</option>
                    <option value="building">功能建筑</option>
                    <option value="trace">生活痕迹</option>
                    <option value="other">其他</option>
                  </select>
                </label>
                {draft ? (
                  <div className="mansion-editor__inline-actions">
                    <button type="button" onClick={() => setDraft({ ...draft, points: draft.points.slice(0, -1) })}>
                      撤回一点
                    </button>
                    <button type="button" disabled={draft.points.length < 3} onClick={completeDraft}>
                      闭合并保存
                    </button>
                  </div>
                ) : (
                  <button
                    type="button"
                    className="is-danger"
                    onClick={() => {
                      setRegions((current) => current.filter((region) => region.id !== selectedRegion!.id));
                      setSelectedId(null);
                      setStatus("区域已删除");
                    }}
                  >删除当前区域</button>
                )}
              </div>
            )}

            <div className="mansion-editor__region-list">
              {regions.length === 0 && <p>还没有区域。点击“新建多边形”后在画面上逐点框选。</p>}
              {regions.map((region) => (
                <button
                  type="button"
                  key={region.id}
                  className={region.id === selectedId ? "is-selected" : ""}
                  onClick={() => {
                    setSelectedId(region.id);
                    setSelectedRectangleId(null);
                    setDraft(null);
                    setRectangleDraft(null);
                    setRectanglePreview(null);
                  }}
                >
                  <i style={{ background: REGION_COLORS[region.kind] }} />
                  <span>{region.label}<small>{region.id} · {region.points.length} 点</small></span>
                </button>
              ))}
            </div>
          </section>

          <section>
            <div className="mansion-editor__section-title">
              <h2>PSD 图层</h2>
              <span>{enabledLayers.size}/{manifest.layers.length}</span>
            </div>
            <div className="mansion-editor__layer-list">
              {manifest.layers.map((layer) => (
                <label key={layer.id}>
                  <input
                    type="checkbox"
                    checked={enabledLayers.has(layer.id)}
                    onChange={() => setEnabledLayers((current) => {
                      const next = new Set(current);
                      next.has(layer.id) ? next.delete(layer.id) : next.add(layer.id);
                      return next;
                    })}
                  />
                  <span>{layer.id}<small>{layer.name}</small></span>
                </label>
              ))}
            </div>
          </section>

          <section>
            <div className="mansion-editor__section-title"><h2>导入 / 导出</h2></div>
            <div className="mansion-editor__export-grid">
              <button type="button" onClick={restoreDefaults}>恢复 v8 默认</button>
              <label className="mansion-editor__file-button">
                导入 JSON
                <input type="file" accept="application/json,.json" onChange={handleImport} />
              </label>
              <button
                type="button"
                disabled={!exportFile}
                onClick={() => exportFile && navigator.clipboard.writeText(JSON.stringify(exportFile, null, 2)).then(() => setStatus("JSON 已复制"))}
              >复制 JSON</button>
              <button
                type="button"
                disabled={!exportFile}
                onClick={() => exportFile && downloadText("mansion-regions.json", JSON.stringify(exportFile, null, 2), "application/json")}
              >下载 JSON</button>
              <button
                type="button"
                disabled={!exportFile}
                onClick={() => exportFile && downloadText("mansion-regions.ts", createTypeScript(exportFile), "text/typescript")}
              >下载 TS 参数</button>
            </div>
          </section>

          <footer>{status} · 已自动保存</footer>
        </aside>
      </section>
    </main>
  );
}
