import { webcrypto } from "node:crypto";
import { IDBFactory } from "fake-indexeddb";
import { act, cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { createAiConfiguration } from "../../game-runtime/airp-configuration";
import { createConnectionVault } from "../../game-infrastructure/airp-direct/connection-vault";
import { AiConnectionHelp, AiConnectionStorage } from "./AiConnectionStorage";
import { UiMotionProvider } from "../../shared/ui/motion/UiMotionProvider";

afterEach(() => { cleanup(); vi.restoreAllMocks(); });
it("offers Save without passwords, restores on reopen, and deletes only after confirmation without network", async () => {
  const vault = createConnectionVault({crypto: webcrypto as unknown as Crypto, indexedDB: new IDBFactory()});
  const store = createAiConfiguration(vault);
  store.patch({baseUrl: "https://synthetic.invalid/v1", commonKey: "synthetic-ui-key"});
  const fetch = vi.spyOn(globalThis, "fetch").mockRejectedValue(Error("Unexpected network"));
  const first = render(<AiConnectionStorage store={store}/>);
  expect(screen.queryByLabelText(/口令/)).toBeNull();
  expect(screen.queryByRole("button", {name: /解锁|锁定/})).toBeNull();
  await waitFor(() => expect(screen.getByRole("button", {name: "保存"})).toBeEnabled());
  expect(await vault.read()).toBeNull();
  fireEvent.click(screen.getByRole("button", {name: "保存"}));
  await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("已保存"));
  expect(screen.getByRole("button", {name: "保存"})).toBeDisabled();
  act(() => store.patch({commonKey: "synthetic-edited-key"}));
  expect(screen.getByRole("status")).toHaveTextContent("有未保存修改");
  expect(screen.getByRole("button", {name: "保存"})).toBeEnabled();
  fireEvent.click(screen.getByRole("button", {name: "保存"}));
  await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("已保存"));
  first.unmount();
  const fresh = createAiConfiguration(vault); render(<UiMotionProvider preference="reduced"><AiConnectionStorage store={fresh}/><AiConnectionHelp store={fresh}/></UiMotionProvider>);
  await waitFor(() => expect(fresh.getSnapshot().commonKey).toBe("synthetic-edited-key"));
  expect(screen.queryByLabelText(/口令/)).toBeNull();
  fireEvent.click(screen.getByText("保存说明", {exact: true}));
  fireEvent.click(screen.getByRole("button", {name: "删除本机配置"}));
  expect(screen.getByRole('dialog', {name: '删除本机配置？'}).closest('.airp-settings-help')).toBeNull();
  expect(await vault.read()).not.toBeNull();
  fireEvent.click(screen.getByRole("button", {name: "取消"}));
  await waitFor(() => expect(screen.queryByRole('dialog')).toBeNull());
  expect(await vault.read()).not.toBeNull();
  fireEvent.click(screen.getByRole("button", {name: "删除本机配置"}));
  fireEvent.click(screen.getByRole("button", {name: "删除配置"}));
  await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("尚未保存"));
  expect(await vault.read()).toBeNull(); expect(fresh.getSnapshot().commonKey).toBe("");
  expect(fetch).not.toHaveBeenCalled();
});
it("shows a safe save error, keeps inputs in memory, and allows retry", async () => {
  const vault = createConnectionVault({crypto: webcrypto as unknown as Crypto, indexedDB: new IDBFactory()});
  const store = createAiConfiguration(vault);
  store.patch({baseUrl: "https://synthetic.invalid/v1", commonKey: "synthetic-ui-key"});
  vi.spyOn(vault, "write").mockRejectedValueOnce(Error("synthetic-secret-error"));
  render(<AiConnectionStorage store={store}/>);
  await waitFor(() => expect(screen.getByRole("button", {name: "保存"})).toBeEnabled());
  fireEvent.click(screen.getByRole("button", {name: "保存"}));
  await waitFor(() => expect(screen.getByRole("alert")).toHaveTextContent("未保存"));
  expect(screen.getByRole("alert")).not.toHaveTextContent("synthetic");
  expect(store.getSnapshot().commonKey).toBe("synthetic-ui-key");
  fireEvent.click(screen.getByRole("button", {name: "保存"}));
  await waitFor(() => expect(screen.getByRole("status")).toHaveTextContent("已保存"));
  expect(screen.queryByRole("alert")).toBeNull();
});
