import { createBattleBindings } from "../game-core/battle/bindings";
import { LEGACY_CONTEXT } from "./legacy-context";

export type * from "../game-core/battle/domain/state";
export type * from "../game-core/battle/domain/effects";
export type * from "../game-core/battle/domain/commands";
export type * from "../game-core/battle/domain/events";
export type * from "../game-core/battle/domain/targets";
export type * from "../game-core/battle/persistence/dto";
export type * from "../game-core/battle/domain/versions";
export const {
  ACTION_EFFECT_DEFINITIONS,
  BATTLE_CONTENT_VERSION,
  BATTLE_EFFECT_DEFINITIONS,
  BATTLE_REACTION_REGISTRY,
  BATTLE_RULES_VERSION,
  BATTLE_SCHEMA_VERSION,
  CHARACTERS,
  DEFAULT_EFFECT_DEPTH_LIMIT,
  DEFAULT_EFFECT_EVENT_BUDGET,
  DOWNED_RETURN_HP,
  FRENZY_ACTIVE_STATUS_ID,
  FRENZY_ATTACK_BONUS,
  FRENZY_WARNING_DURATION,
  FRENZY_WARNING_STATUS_ID,
  HAND_BONUSES,
  LAYER_MULTIPLIERS,
  MAX_HP,
  MAX_LAYER,
  PARTY_ORDER,
  REROLLS_PER_ROUND,
  STALL_GRACE_ROUNDS,
  actOnEnemy,
  actOnMember,
  activateScheduledFrenzyForNextRoundTransition,
  advanceRngStream,
  advanceStatusDurations,
  applyFrenzyRecoilTransition,
  applyNumericModifiers,
  assertExpeditionInvariants,
  assessStalling,
  attackEnemy,
  beginNextRoundTransition,
  blockIntent,
  buildActionEffectContribution,
  canActWith,
  canToggleLoad,
  canUndo,
  cloneBattleLoadout,
  cloneBattleState,
  collectEventReactions,
  collectExpeditionInvariantViolations,
  compareOrderedSources,
  compareReactionBindings,
  compileEffectRuntime,
  completeNextRoundAfterFrenzyTransition,
  createBattleCompletionOutput,
  createBattleLoadoutSettlement,
  createBattleRngState,
  createBattleSaveDto,
  createEmptyBattleLoadout,
  createExpedition,
  createExpeditionFromSeed,
  createExpeditionState,
  createExpeditionStateFromInput,
  createExpeditionTransition,
  createRngCursor,
  deserializeBattleState,
  dispatchBattleCommand,
  drawRngValue,
  endTurn,
  evaluateHand,
  finishEnemyTurn,
  getBattlePhase,
  getBlocked,
  getEffectiveFaceQuality,
  getEnemyFrenzyActiveStatus,
  getEnemyFrenzyWarningStatus,
  getEnemyTotalHp,
  getExpeditionStatus,
  getFace,
  getFaceValue,
  getFrenzyWarningRounds,
  getGildFaceCount,
  getGreedSummary,
  getIncomingDamageFor,
  getIntentThreat,
  getLayerPayout,
  getLayerSettlement,
  getPartyTotalHp,
  getPotentialDamage,
  getReadyDamage,
  getRoundOutcome,
  getRustFaceCount,
  getRustableFaceCapacity,
  getStateFace,
  getTotalThreat,
  getTrackedRngSnapshot,
  getUndoLabel,
  goDeeper,
  goDeeperTransition,
  hasEnemyFrenzyWarning,
  hasPendingAction,
  hasUnloadedDice,
  healMember,
  isDieDowned,
  isEnemyDefeated,
  isEnemyFrenzied,
  leaveExpedition,
  leaveExpeditionTransition,
  mergeEffectResolutionOptions,
  migrateBattleSaveDto,
  mulberry32,
  nextRound,
  performInitialRoll,
  performReroll,
  performToggleLoad,
  performUndo,
  prepareEnemyTurn,
  prepareEnemyTurnTransition,
  rankHand,
  rerollDice,
  resolveAtomicEffects,
  resolveEffectsCommand,
  resolveEnemyIntentTransition,
  resolveEnemyTurnStep,
  rollDice,
  serializeBattleState,
  settleEnemyTurnTransition,
  startLayerTransition,
  stealFrom,
  targetRefKey,
  toggleLoad,
  undo
} = createBattleBindings(LEGACY_CONTEXT);

export const EXPENSIVE_HEAL_EFFECT_ID = "action.expensive-heal";
