import {expect, it} from "vitest";
import {earnedAppraisalFixture} from "../testing/appraisal-fixture";
import {publicGameAppraisal} from "./appraisals";
import {readD5Archive} from "../versions/d5-validate";
import {D5_RUN_READERS} from "../../game-core/session";
import {projectGameNode} from "./projection";

it("freezes copy before departure, earns real loot, trades once, restores history and retains it through the next preparation", async () => {
  const f = await earnedAppraisalFixture(), record = f.raw();
  const shop = () => f.runtime.queries.shop(f.raw())!;
  const item = shop().loot!.items.find(i => i.generatedAppraisal)!;
  expect(item).toBeDefined();
  const slot = f.packet.context.rules.appraisalSlots!.find(s => s.instanceId === item.instanceId)!;
  const copy = f.proposal.appraisalItems!.find(c => c.slotKey === slot.key)!;
  const serialized = JSON.stringify(item.generatedAppraisal);
  expect(serialized).toContain(copy.unknownName); expect(serialized).not.toContain(copy.name);
  expect(item.generatedAppraisal!.identified).toBeNull(); expect(item.stackable).toBe(false);
  expect(record.airpGame!.gm.jobs[0].attempts).toHaveLength(1);
  const publicScene = projectGameNode(record, f.catalog).program.sources[0].text;
  expect(publicScene).toContain(copy.unknownName); expect(publicScene).not.toContain(copy.name);
  expect(publicScene).not.toContain(copy.sold.text);
  const journey = f.runtime.queries.journey(record)!;
  expect(journey.appraisalLoot[item.instanceId]).toEqual({unknownName: copy.unknownName, appearance: copy.appearance});
  expect(JSON.stringify(journey.appraisalLoot)).not.toContain(copy.name);
  const baseFunds = record.snapshot.campaign.funds.party;
  await f.send({type: "appraise-loot", shopId: shop().shopId, quoteVersion: shop().loot!.quoteVersion, instanceId: item.instanceId});
  const known = shop().loot!.items.find(i => i.instanceId === item.instanceId)!;
  expect(known.generatedAppraisal!.identified).toMatchObject({name: copy.name, rarity: slot.rarity, appraisal: copy.appraisal});
  expect(shop().funds).toBe(baseFunds - slot.appraisalFee);
  await expect(f.send({type: "appraise-loot", shopId: shop().shopId, quoteVersion: shop().loot!.quoteVersion, instanceId: item.instanceId})).rejects.toThrow();
  await expect(f.send({type: "sell-loot", shopId: shop().shopId, quoteVersion: shop().loot!.quoteVersion, instanceId: item.instanceId, quantity: 2})).rejects.toThrow(/逐件/);
  await f.send({type: "sell-loot", shopId: shop().shopId, quoteVersion: shop().loot!.quoteVersion, instanceId: item.instanceId});
  expect(shop().funds).toBe(baseFunds - slot.appraisalFee + slot.salePrice);
  expect(shop().loot!.history.filter(t => t.item.instanceId === item.instanceId)).toHaveLength(2);
  expect(shop().loot!.history.find(t => t.kind === "sell" && t.item.instanceId === item.instanceId)!.generatedAppraisal!.identified!.sold).toEqual(copy.sold);
  const exported = await f.runtime.application.exportSave("formal-airp"); if (!exported.ok) throw Error("export failed");
  const restored = readD5Archive(exported.archive, f.catalog, D5_RUN_READERS);
  expect(publicGameAppraisal(restored, known)).toEqual(known.generatedAppraisal);
  const attempts = restored.airpGame!.gm.jobs[0].attempts;
  expect(attempts).toHaveLength(1);
  await f.flow.prepare({...f.departure, runId: "another-trip"});
  expect(shop().loot!.history.find(t => t.kind === "appraise" && t.item.instanceId === item.instanceId)!.generatedAppraisal!.identified!.appraisal).toEqual(copy.appraisal);
  expect(f.raw().airpGame!.gm.jobs[0].attempts).toEqual(attempts);
}, 120_000);
