import { expect, it } from "vitest";
import { formalAirpFixture } from "../testing/airp-game-fixture";
import { directorPlan, directorScene } from "../testing/airp-director-playthrough";
import { directorTestMaterial } from "../testing/airp-director-fixture";
import { AIRP_GAME_CATALOG } from "../../game-runtime/airp-game-context";
import { airpGameView, pendingHomeBoundary } from "../../game-runtime/airp-game-runtime";
import { directorView } from "../../game-runtime/airp-director-view";
import { nextD5PlayCommand } from "../testing/d5-playthrough";
import { emptySettlementProposal } from "../airp-settlement/context";
import { emptyUsage } from "../airp-generation/contracts";
import { readD5Archive } from "../versions/d5-validate";
import { D5_RUN_READERS } from "../../game-core/session";
import { clcProposal } from "../testing/airp-expedition-gm-fixture";
import { lowR8Source } from "../../content/presentation/airp/low-r8-source";

it("formal return requires feedback, settlement and explicit delivery; then closure reaches the next day GM", async () => {
  const f = await formalAirpFixture(); await f.flow.sync();
  expect(f.raw().airpGame?.preparation).toBeNull();
  const wf = { read: async () => f.raw(), send: f.send };
  await f.send({ type: "airp-director-configure", material: directorTestMaterial(), lowMaterial: lowR8Source, lowReadVersion: 2, lowContextVersion: 6 });
  expect(directorView(f.raw())!.context.facts.some(s => s.id === "assets:current")).toBe(true);
  await directorPlan(wf, { kind: "fixed", definitionId: "ripple.elora.old-medicine-case" });
  await f.send({ type: "advance-phase" }); await f.send({ type: "advance-phase" });
  const eventId = f.raw().airpDirector!.events[0].id;
  await directorScene(wf, eventId);
  expect(f.raw().airpDirector!.jobs.filter(j => j.kind === "scene").every(j => j.lowFrame && !j.attempts.some(a => a.stage === "planning"))).toBe(true);
  await f.send({ type: "airp-director-choose", eventId, choiceId: "participate" });
  await directorScene(wf, eventId); await directorScene(wf, eventId);
  await f.send({ type: "airp-director-choose", eventId, choiceId: "participate" });
  await expect(f.send({ type: "airp-director-deliver", eventId })).rejects.toThrow();
  const planId = await f.flow.prepare(f.departure), gmProposal = clcProposal(await f.flow.gm.read());
  await f.flow.gm.begin(planId, { id: "gm-return", stage: "plan", model: "test-mock", connectionHash: "1".repeat(64), at: 1 });
  await f.flow.gm.result(planId, "gm-return", JSON.stringify(gmProposal), emptyUsage(), 2); await f.flow.gm.accept(planId);
  const permit = await f.flow.gm.departurePermit(planId);
  expect(f.raw().airpGame!.gm.jobs[0].frames[0].context.rules.commissions[0].eventId).toBe(eventId);
  await f.send({ type: "start-expedition", ...permit.departure }); await f.flow.sync();
  let steps = 0;
  while (f.raw().snapshot.run && steps++ < 600) {
    const node = airpGameView(f.raw())?.node;
    if (node) await f.flow.nodes.skip(node.id);
    const cmd = nextD5PlayCommand(AIRP_GAME_CATALOG, f.raw()), run = f.raw().snapshot.run;
    await f.send(cmd.type === "choose-exit" && run?.kind === "expedition" && run.state.run.layer >= 3 ? { ...cmd, choice: "leave" } : cmd); await f.flow.sync();
    if (steps % 8 === 0) await new Promise(resolve => setTimeout(resolve, 0));
  }
  expect(f.raw().snapshot.run).toBeNull();
  let e = f.raw().airpDirector!.events.find(e => e.id === eventId)!;
  expect(e).toMatchObject({ status: "feedback", actionOutcome: "succeeded", delivery: { status: "pending" } });
  for (let i = 0; i < 4 && !directorView(f.raw())!.entrances.some(e => e.event.id === eventId); i++) await f.send({ type: "advance-phase" });
  await directorScene(wf, eventId);
  expect(f.raw().airpDirector!.events[0]).toMatchObject({ status: "ready", delivery: { status: "pending" } });
  const feedback = f.raw().airpDirector!.jobs.find(j => j.scene?.role === "feedback")!;
  expect(feedback.scene!.progress).toMatchObject({ status: "feedback", actionOutcome: "succeeded", delivery: { status: "pending" }, runResult: { outcome: "extracted", deepestLayer: 3 } });
  expect(feedback.scene!.progress!.runResult!.partyIds).toEqual(f.departure.partyIds);
  expect(feedback.lowFrame!.scene.currentTurn).toContain("本趟实际同行者");
  expect(feedback.scene!.progress!.readScenes.map(s => s.role)).toEqual(["offer", "acceptance", "action"]);
  expect(feedback.lowFrame!.scene.currentTurn).toContain("任务目标已带回但尚未交付");
  expect(feedback.lowFrame!.messages.at(-1)!.content.endsWith(feedback.lowFrame!.scene.currentTurn!)).toBe(true);
  for (const p of feedback.scene!.previous) {
    expect(feedback.scene!.memories.some(m => m.id === `memory:${p.sceneId}`)).toBe(false);
    expect(feedback.scene!.facts.some(m => m.id === `memory:${p.sceneId}`)).toBe(false);
    expect(feedback.lowFrame!.scene.userInput).toContain(JSON.stringify(p.text));
  }
  await expect(f.send({ type: "airp-director-deliver", eventId })).rejects.toThrow(/整理/);
  const task = await f.flow.settleHome(), job = (await f.flow.settlement.read()).ledger.jobs.find(j => j.id === task)!, input = job.frames.at(-1)!.input;
  expect(input.lifecycle).toEqual([{ kind: "run", id: f.departure.runId, basisIds: [f.raw().airpDirector!.events[0].delivery!.returnFactId] }]);
  expect(job.frames[0].materials.cards.find(c => c.actorId === "elora")!.text).toContain("艾洛拉");
  expect(job.frames[0].materials.world.map(w => ({ id: w.id, text: w.text, digest: w.digest }))).toEqual(feedback.lowFrame!.sources.filter(s => s.kind === "world" || s.kind === "player").map(s => ({ id: s.id, text: s.text, digest: s.sha256 })));
  const proposal = emptySettlementProposal(input), fact = input.evidence.find(s => s.role === "current" && s.kind === "program-fact")!;
  proposal.affinity = [{ grantId: input.grants.find(g => g.kind === "affinity")!.id, gradeId: "closer", reason: "测试模型：具体合作后更信任。", basisIds: [fact.id] }];
  proposal.actors = [{ grantId: input.grants.find(g => g.kind === "actor")!.id, locationId: "plaza", conditions: { add: [{ id: "tired", untilPhase: input.state.phase + 2, endConditionId: null }], removeIds: [] }, basisIds: [fact.id] }];
  proposal.memory.points = [{ kind: "fact", text: "测试结算：艾洛拉在广场确认巡守反馈，合作增进信任，仍有疲惫。", speakerId: null, knownBy: fact.knownBy, basisIds: [fact.id] }];
  proposal.memory.open = [{ kind: "fact", text: "等待玩家明确交付。", speakerId: null, knownBy: fact.knownBy, basisIds: [fact.id], key: "delivery", until: "event-end" }];
  await f.flow.settlement.begin(task, { id: "home-mock", model: "test-mock", connectionHash: "3".repeat(64), at: 1 });
  await f.flow.settlement.result({ jobId: task, attemptId: "home-mock", output: JSON.stringify(proposal), usage: emptyUsage(), at: 2 });
  await f.flow.settlement.apply(task);
  expect(pendingHomeBoundary(f.raw())).toBeNull();
  expect(f.raw().airpGame!.settlement.state.affinity).toEqual([{ actorId: "elora", value: 1 }]);
  const share = f.raw().facts.filter(fact => fact.kind === "airp-game" && fact.payload.settlement).at(-1);
  expect(share?.kind === "airp-game" && share.payload.settlement?.locationActorIds).toEqual(["elora"]);
  const loot = f.raw().snapshot.campaign.loot;
  await f.send({ type: "airp-director-open", eventId });
  expect(f.raw().airpDirector!.jobs.some(j => j.id === f.raw().airpDirector!.reading!.jobId)).toBe(false);
  await f.send({ type: "airp-director-deliver", eventId });
  expect(f.raw().snapshot.campaign.loot).toEqual(loot);
  e = f.raw().airpDirector!.events[0]; expect(e).toMatchObject({ status: "ready", delivery: { status: "confirmed" } });
  await directorScene(wf, eventId);
  expect(f.raw().airpDirector!.events[0].status).toBe("resolved");
  const resultScene = f.raw().airpDirector!.jobs.find(j => j.scene?.eventId === eventId && j.scene.role === "result")!;
  expect(resultScene.scene!.progress).toMatchObject({ status: "ready", actionIndex: 1, delivery: { status: "confirmed" } });
  expect(resultScene.scene!.progress!.readScenes.at(-1)).toMatchObject({ sceneId: feedback.id, role: "feedback" });
  expect(resultScene.lowFrame!.scene.currentTurn).toContain("不重演迎接");
  expect(resultScene.lowFrame!.sources).toEqual(feedback.lowFrame!.sources);
  expect(resultScene.scene!.settlementRead?.some(line => line.text.includes("我等你"))).toBe(true);
  const finalId = await f.flow.settleHome(), finalJob = (await f.flow.settlement.read()).ledger.jobs.find(j => j.id === finalId)!, finalInput = finalJob.frames[0].input;
  const finalProposal = emptySettlementProposal(finalInput), finalFact = finalInput.evidence.find(s => s.role === "current" && s.kind === "program-fact")!;
  finalProposal.memory.points = [{ kind: "fact", text: "测试结算：任务目标已明确交付，结果已读，事件结束。", speakerId: null, knownBy: finalFact.knownBy, basisIds: [finalFact.id] }];
  // Program lifecycle closes event-scoped pending delivery even if the model emits no close.
  expect(finalInput.lifecycle).toContainEqual({ kind: "event", id: eventId, basisIds: [finalFact.id] });
  expect(finalProposal.memory.close).toEqual([]);
  finalProposal.memory.priorReceiptIds = finalInput.priorReceipts.map(r => r.id);
  await f.flow.settlement.begin(finalId, { id: "final-mock", model: "test-mock", connectionHash: "3".repeat(64), at: 3 });
  await f.flow.settlement.result({ jobId: finalId, attemptId: "final-mock", output: JSON.stringify(finalProposal), usage: emptyUsage(), at: 4 });
  await f.flow.settlement.apply(finalId);
  expect(f.raw().airpGame!.settlement.openThreads).toEqual([]);
  const context = directorView(f.raw())!.context;
  expect(context.memories.some(m => m.text.includes("任务目标已明确交付"))).toBe(true);
  expect(context.facts.some(m => m.text.includes('"value":1'))).toBe(true);
  expect(context.facts.find(m => m.id.startsWith("assets:"))!.text).not.toContain("definitionId");
  expect(context.world.followups.find(x => x.parentId === eventId)?.eligible).toBe(true);
  await f.send({ type: "advance-phase" }); await f.send({ type: "advance-phase" });
  await f.send({ type: "airp-director-prepare-day" });
  expect(f.raw().airpDirector!.jobs.at(-1)!.planning!.memories.some(m => m.text.includes("任务目标已明确交付"))).toBe(true);
  const exported = await f.runtime.application.exportSave("formal-airp"); if (!exported.ok) throw Error("export failed");
  expect(readD5Archive(exported.archive, AIRP_GAME_CATALOG, D5_RUN_READERS)).toEqual(f.raw());
}, 240000);
