import { act, cleanup, fireEvent, render, screen } from "@testing-library/react";
import { afterEach, expect, it, vi } from "vitest";
import { manorClientFixture } from "../../game-client/testing/manor";
import { journeyOf, playToJourney } from "../../game-client/testing/journey-flow";
import { GameSessionScope } from "../../game-client/react";
import { SceneTransitionProvider } from "../../shared/transition";
import { ManorBattleBinding } from "./ManorBattleBinding";
const fixtures: Awaited<ReturnType<typeof manorClientFixture>>[] = [];
afterEach(() => {cleanup(); fixtures.splice(0).forEach(f=>f.session.dispose()); sessionStorage.clear(); vi.useRealTimers();});
const flush = async () => {for (let i=0;i<8;i++) await act(async () => {await vi.runAllTimersAsync();});};
it("event story surrounds the real reading decision; dialogue never commits rewards and resumes across remount", async () => {
  const f=await manorClientFixture(19,2);fixtures.push(f);
  await playToJourney(f,v=>v.expedition?.node === "room-complete");
  vi.useFakeTimers({toFake:["setTimeout","clearTimeout"]});
  const mount=() => render(<GameSessionScope session={f.session}><SceneTransitionProvider><ManorBattleBinding onSettle={()=>{}} uiSkin="old-manor"/></SceneTransitionProvider></GameSessionScope>);
  let mounted=mount();
  await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"继续前进"}));});
  await flush();
  expect(screen.queryByRole("dialog")).toBeNull();
  expect(screen.getByRole("region",{name:"ADV 对话"})).toBeVisible();
  expect(screen.queryByRole("main",{name:"克雷格旧庄园战斗界面"})).toBeNull();
  const committed=f.session.getSnapshot().record!.head;
  if(screen.queryByRole("button",{name:"显示全文"})) await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"显示全文"}));});
  await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"下一句"}));});
  await flush();
  expect(document.querySelector('.rp-adv__actor[data-character="kororo"]')).toHaveAttribute("data-expression","k");
  if(screen.queryByRole("button",{name:"显示全文"})) await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"显示全文"}));});
  const dialogue=document.querySelector(".abyssa-dialogue__content")!.textContent;
  mounted.unmount(); mounted=mount(); await flush();
  if(screen.queryByRole("button",{name:"显示全文"})) await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"显示全文"}));});
  expect(document.querySelector(".abyssa-dialogue__content")).toHaveTextContent(dialogue!);
  expect(f.session.getSnapshot().record!.head).toEqual(committed);
  await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"跳过本段对白"}));});await flush();
  await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"阅读迎宾簿"}));});await flush();
  expect(journeyOf(f).lastEvent?.method).toBe("read");
  expect(screen.getByRole("main",{name:"庄园记录"})).toBeVisible();
  expect(screen.queryByRole("dialog")).toBeNull();
  const result=f.session.getSnapshot().record!.head;
  await act(async()=>{fireEvent.click(screen.getByRole("button",{name:"跳过本段对白"}));});await flush();
  expect(screen.getByRole("button",{name:"继续前进"})).toBeEnabled();
  expect(f.session.getSnapshot().record!.head).toEqual(result);
},60000);
