import { describe, expect, it } from "vitest";
import type {
  MansionPsdManifest,
  MansionRectangle,
  MansionRegion
} from "../../shared/domain/mansion/regions";
import {
  cleanRegionId,
  createRegionTypeScript,
  makeRegionFile,
  rectangleFromPoints,
  roundCoordinate
} from "./region-editor-model";

const manifest: MansionPsdManifest = {
  version: 1,
  source: "mansion.psd",
  width: 5162,
  height: 1910,
  layers: []
};

describe("mansion region editor model", () => {
  it("rounds and clamps normalized coordinates", () => {
    expect(roundCoordinate(-0.1)).toBe(0);
    expect(roundCoordinate(1.1)).toBe(1);
    expect(roundCoordinate(0.12345678)).toBe(0.123457);
  });

  it("creates a normalized rectangle regardless of drag direction", () => {
    expect(rectangleFromPoints(
      { x: 0.8, y: 0.7 },
      { x: 0.2, y: 0.1 }
    )).toEqual({ x: 0.2, y: 0.1, width: 0.6, height: 0.6 });
  });

  it("normalizes user-entered region ids", () => {
    expect(cleanRegionId("  Great Hall 01!  ")).toBe("great-hall-01");
    expect(cleanRegionId("Room_A-2")).toBe("room_a-2");
  });

  it("builds a versioned, rounded file without mutating editor state", () => {
    const regions: MansionRegion[] = [{
      id: "tower",
      label: "Tower",
      kind: "building",
      points: [{ x: 0.12345678, y: -0.2 }, { x: 1.2, y: 0.5 }]
    }];
    const rectangles: MansionRectangle[] = [{
      id: "hall",
      label: "Hall",
      kind: "room",
      rect: { x: 0.11111119, y: 0.2, width: 0.4, height: 1.1 }
    }];
    const originalRegions = structuredClone(regions);
    const originalRectangles = structuredClone(rectangles);

    const file = makeRegionFile(manifest, regions, rectangles);

    expect(file).toMatchObject({
      version: 2,
      canvas: { width: 5162, height: 1910 },
      regions: [{ points: [{ x: 0.123457, y: 0 }, { x: 1, y: 0.5 }] }],
      rectangles: [{ rect: { x: 0.111111, y: 0.2, width: 0.4, height: 1 } }]
    });
    expect(regions).toEqual(originalRegions);
    expect(rectangles).toEqual(originalRectangles);
  });

  it("emits the three TypeScript constants consumed by the runtime", () => {
    const file = makeRegionFile(manifest, [], []);
    const source = createRegionTypeScript(file);

    expect(source).toContain("Generated by the Abyssa mansion region editor");
    expect(source).toContain("export const MANSION_CANVAS");
    expect(source).toContain("export const MANSION_RECTANGLES");
    expect(source).toContain("export const MANSION_REGIONS");
  });
});
