import type {
  MansionPsdManifest,
  MansionRectangle,
  MansionRegion,
  MansionRegionFile,
  NormalizedPoint,
  NormalizedRectangle
} from "../../shared/domain/mansion/regions";

export function clamp(value: number, min: number, max: number) {
  return Math.min(max, Math.max(min, value));
}

export function roundCoordinate(value: number) {
  return Number(clamp(value, 0, 1).toFixed(6));
}

export function rectangleFromPoints(
  start: NormalizedPoint,
  end: NormalizedPoint
): NormalizedRectangle {
  return {
    x: roundCoordinate(Math.min(start.x, end.x)),
    y: roundCoordinate(Math.min(start.y, end.y)),
    width: roundCoordinate(Math.abs(end.x - start.x)),
    height: roundCoordinate(Math.abs(end.y - start.y))
  };
}

export function cleanRegionId(value: string) {
  return value
    .trim()
    .toLowerCase()
    .replace(/\s+/g, "-")
    .replace(/[^a-z0-9_-]/g, "");
}

export function makeRegionFile(
  manifest: MansionPsdManifest,
  regions: readonly MansionRegion[],
  rectangles: readonly MansionRectangle[]
): MansionRegionFile {
  return {
    version: 2,
    canvas: { width: manifest.width, height: manifest.height },
    rectangles: rectangles.map((rectangle) => ({
      ...rectangle,
      rect: {
        x: roundCoordinate(rectangle.rect.x),
        y: roundCoordinate(rectangle.rect.y),
        width: roundCoordinate(rectangle.rect.width),
        height: roundCoordinate(rectangle.rect.height)
      }
    })),
    regions: regions.map((region) => ({
      ...region,
      points: region.points.map((point) => ({
        x: roundCoordinate(point.x),
        y: roundCoordinate(point.y)
      }))
    }))
  };
}

export function createRegionTypeScript(file: MansionRegionFile) {
  return `// Generated by the Abyssa mansion region editor.\n` +
    `export const MANSION_CANVAS = ${JSON.stringify(file.canvas, null, 2)} as const;\n\n` +
    `export const MANSION_RECTANGLES = ${JSON.stringify(file.rectangles, null, 2)} as const;\n\n` +
    `export const MANSION_REGIONS = ${JSON.stringify(file.regions, null, 2)} as const;\n`;
}
