import { expect, it } from "vitest";
import { MemoryGameDatabase, MemoryGameStore } from "../../game-infrastructure/storage/memory";
import type { AnyGameRecord, AnyReceipt, D5GameRecord } from "../index";
import { createPlayerRuntime } from "../../game-runtime/player-runtime";
import { directorView } from "../../game-runtime/airp-director-view";
import { householdDirectorDocuments } from "../../content/presentation/airp/household-documents";
import { householdLowR8Source } from "../../content/presentation/airp/low-r8-source";

it.each(["hub", "airp-demo", "airp-director"] as const)("starts %s in the unified formal roster without a connection or day request", async startAt => {
  const db = new MemoryGameDatabase<AnyGameRecord, AnyReceipt>(), store = new MemoryGameStore(db);
  const runtime = createPlayerRuntime(store, {newId: () => "test", newSeed: () => 19, close() {}});
  const request = {saveId: "roster", epoch: "epoch", clientRequestId: "create", startAt};
  expect(await runtime.application.createNewGame(request)).toMatchObject({ok: true});
  const read = () => structuredClone(db.records.get(request.saveId)! as D5GameRecord);
  const initial = read(), campaign = initial.snapshot.campaign;
  expect(initial.contentRef.contentVersion).toBe(28);
  expect(initial.facts.at(-1)!.payload).toMatchObject({type: "game-start-selected", startAt: "hub", openingFlowVersion: 1});
  expect(initial.airpDirect).toBeUndefined();
  const flow = runtime.airpGame.forSave(request.saveId, 28, request.epoch);
  await flow.sync();
  const current = read(), view = directorView(current)!;
  expect(view.context.capabilities.actorIds).toHaveLength(6);
  expect(view.context.world.availableActorIds).toEqual(expect.arrayContaining(["abyssa", "marietta"]));
  expect(current.airpGame!.settlement.policy.actorIds).toHaveLength(6);
  expect(current.airpGame!.material).toEqual(householdLowR8Source);
  expect(current.airpDirector).toMatchObject({materialHash: null, materials: {}, jobs: [], residentCast: {version: 1}, lowReadVersion: 6, lowContextVersion: 21});
  expect(current.snapshot.campaign).toEqual(campaign);
  expect(current.airpDirector!.lowMaterial!.sources).toEqual(householdDirectorDocuments.filter(s => ["world", "character", "player"].includes(s.kind)));
  expect(runtime.queries.memoryJournal(current)).toMatchObject({status: "ready", entries: [expect.anything(), expect.anything()]});
  await flow.sync();
  expect(read()).toEqual(current);
  expect(await runtime.application.createNewGame(request)).toMatchObject({ok: true, replayed: true});
  expect(read()).toEqual(current);
  const archive = await runtime.application.exportSave(request.saveId);
  if (!archive.ok) throw Error("export");
  const recoveryStore = new MemoryGameStore(new MemoryGameDatabase<AnyGameRecord, AnyReceipt>());
  const recovery = createPlayerRuntime(recoveryStore, {newId: () => "restore", newSeed: () => 19, close() {}});
  expect(await recovery.application.restoreSave({archive: archive.archive, clientRequestId: "restore"})).toMatchObject({ok: true});
  expect(await recovery.application.open(request.saveId)).toEqual({ok: true, record: current});
}, 30000);
