import { directorView } from "../../game-runtime/airp-director-view";
import { expect, it } from "vitest";
import { shopWaveFixture } from "./shop-wave-fixture";
import { shopFixture } from "./shop-foundation-fixture";
import { playOrdinaryDrops, settleOrdinaryDrops } from "./ordinary-drops-fixture";
import { equipmentTargets } from "../../game-core/contracts/equipment";
import { validateD5Record } from "../versions/d5-validate";
import { D5_RUN_READERS } from "../../game-core/session";
import { SHOP_AIRP_CATALOG } from "../../game-runtime/shop-wave-context";

it("uses committed dates and atomic purchases, rejects stale or bypassed quotes, and replays once", async () => {
  const f = await shopWaveFixture();
  expect(f.read().contentRef.contentVersion).toBe(23);
  expect(f.runtime.queries.shop(f.read())!.products).toHaveLength(5);
  expect((await f.send(f.quote("spare-blade"))).result.ok).toBe(false);
  await f.day(2);
  const before = f.read(), purchase = await f.commit(f.quote("iron-bracer"));
  if (!purchase.result.ok) throw Error("purchase");
  const after = f.read();
  expect(after.snapshot.campaign.funds.party).toBe(3120);
  expect(after.snapshot.campaign.inventory).toHaveLength(1);
  expect(after.snapshot.campaign.inventory[0].grantId).toBe(purchase.result.receipt!.factIds[0]);
  expect(await f.runtime.application.dispatch(purchase.input)).toMatchObject({ok: true, replayed: true});
  expect(f.read()).toEqual(after);
  expect((await f.send(f.quote("iron-bracer"))).result.ok).toBe(false);
  expect((await f.send({...f.quote("spare-blade"), quantity: 2})).result.ok).toBe(false);
  expect((await f.send({type: "purchase-supply", shopId: "shop.mansion", definitionId: "item.ward", quantity: 1, quoteVersion: 2})).result.ok).toBe(false);
  expect(f.read()).toEqual(after);
  expect(await f.runtime.application.dispatch({...purchase.input, clientRequestId: "stale-head"})).toMatchObject({ok: false, error: {code: "conflict"}});
  await f.day(3);
  const oldQuote = {...f.quote("spare-blade"), day: 2};
  expect((await f.send(oldQuote)).result).toMatchObject({ok: false, error: {code: "quote-expired"}});
  const stock = f.read().snapshot.campaign.shop!;
  const offer = stock.offers[0].productId;
  await f.commit({...f.quote(""), productId: offer});
  expect(f.read().snapshot.campaign.shop!.offers).toEqual([{productId: offer, remaining: 0}]);
  expect(f.runtime.queries.shop(f.read())!.products.find(p => p.id === offer)?.purchaseMaximum).toBe(0);
  await f.commit({type: "advance-phase"});
  expect(f.read().snapshot.campaign.shop!.offers).toEqual([{productId: offer, remaining: 0}]);
  expect(before.snapshot.campaign.shop!.seed).toBe(f.read().snapshot.campaign.shop!.seed);
  await f.day(6);
  const poor = f.read();
  expect((await f.send(f.quote("emergency-pouch"))).result).toMatchObject({ok: false, error: {code: "insufficient-funds"}});
  expect(f.read()).toEqual(poor);
});

it("retains the seed, bags, ownership and future offers through copy and exact restore", async () => {
  const f = await shopWaveFixture(); await f.day(3); await f.commit(f.quote("spare-blade"));
  const before = f.read(), exported = await f.runtime.application.exportSave(f.saveId);
  if (!exported.ok) throw Error("export");
  const restored = shopFixture();
  expect(await restored.runtime.application.restoreSave({archive: exported.archive, clientRequestId: "restore"})).toMatchObject({ok: true});
  expect(restored.read()).toEqual(before);
  expect(await f.runtime.application.importSave({saveId: "wave-copy", epoch: "copy", clientRequestId: "copy", archive: exported.archive})).toMatchObject({ok: true});
  const copied = await f.runtime.application.open("wave-copy");
  if (!copied.ok || copied.record.schemaVersion !== 4) throw Error("copy");
  expect(copied.record.snapshot.campaign.shop).toEqual(before.snapshot.campaign.shop);
  const other = await shopWaveFixture(copied.record);
  await f.day(8); await other.day(8);
  expect(other.read().snapshot.campaign.shop).toEqual(f.read().snapshot.campaign.shop);
  const tampered = structuredClone(f.read()); tampered.snapshot.campaign.shop!.seed = "forged";
  expect(() => validateD5Record(tampered, f.catalog, D5_RUN_READERS)).toThrow();
});

it.each(["extract", "wipe", "clear"] as const)("keeps bought equipment on %s and refreshes exactly once when settlement crosses midnight", async outcome => {
  const f = await shopWaveFixture(); await f.day(2); await f.commit(f.quote("iron-bracer"));
  const item = f.read().snapshot.campaign.inventory[0];
  const def = f.catalog.data.equipment[item.definitionId];
  const target = equipmentTargets(f.catalog.data, "kael", def)[0];
  await f.commit({type: "equip-equipment", instanceId: item.instanceId, ownerId: "kael", targetFaceId: target.id});
  await f.day(2, "night");
  const before = f.read(), runId = `wave:${outcome}`;
  await f.commit({type: "start-expedition", runId, routeId: "old-manor.first-clear", partyIds: f.catalog.data.initialParty, itemIds: ["item.food", "item.potion"], seed: 19});
  const run = f.read().snapshot.run;
  if (run?.kind !== "expedition") throw Error("run");
  expect(run.state.run.party[0].config.faces.find(face => face.id === target.id)?.power).toBe(target.power + 1);
  expect(run.state.run.supplies).toHaveLength(2);
  expect((await f.send({type: "unequip-equipment", instanceId: item.instanceId, ownerId: "kael"})).result.ok).toBe(false);
  const fixture = {...f, before, runId};
  await playOrdinaryDrops(fixture, outcome);
  expect(f.read().snapshot.campaign.clock).toEqual({day: 2, phase: "night"});
  const settled = await settleOrdinaryDrops(fixture);
  const campaign = f.read().snapshot.campaign;
  expect(campaign.clock).toEqual({day: 3, phase: "dawn"});
  expect(campaign.shop!.offers).toHaveLength(1);
  expect(campaign.inventory[0]).toMatchObject({...item, targetFaceId: target.id, location: {kind: "equipped", ownerId: "kael"}});
  expect(campaign.loot!.some(loot => loot.definitionId.startsWith("equipment."))).toBe(false);
  const stock = structuredClone(campaign.shop);
  expect(await f.runtime.application.dispatch(settled.input)).toMatchObject({ok: true, replayed: true});
  expect(f.read().snapshot.campaign.shop).toEqual(stock);
  await f.commit({type: "unequip-equipment", instanceId: item.instanceId, ownerId: "kael"});
  expect(f.read().snapshot.campaign.inventory[0]).not.toHaveProperty("targetFaceId");
  if (outcome === "extract") {
    await f.commit(f.quote("spare-blade"));
    const purchased = f.read().snapshot.campaign.inventory;
    const eventId = f.catalog.data.progression.gift.eventId;
    const event = f.runtime.queries.progression(f.read())!.events.find(e => e.eventId === eventId)!;
    await f.commit({type: "begin-story", eventId, basisId: event.basisId!});
    const story = f.read().snapshot.campaign.stories.find(s => s.eventId === eventId)!;
    await f.commit({type: "advance-story", sessionId: story.id, step: story.step, choice: "skip"});
    await f.commit({type: "complete-story", sessionId: story.id});
    expect(f.read().snapshot.campaign.inventory).toHaveLength(purchased.length + 2);
    expect(f.read().snapshot.campaign.inventory.slice(0, purchased.length)).toEqual(purchased);
    await f.day(4); await f.commit(f.quote("emergency-pouch"));
    for (const id of ["equipment.spare-blade", "equipment.emergency-pouch"]) expect(f.read().snapshot.campaign.inventory.filter(i => i.definitionId === id)).toHaveLength(2);
  }
}, 180_000);

it("opens content24 through the formal AIRP host with the same deterministic shop", async () => {
  const f = shopFixture();
  expect(await f.runtime.application.create({protocolVersion: 4, contentVersion: 24, profileId: "profile.demo.first-run", saveId: f.saveId, epoch: "airp-wave", clientRequestId: "new-airp"})).toMatchObject({ok: true});
  await f.commit({type: "select-game-start", startAt: "airp-director"});
  expect(f.read().contentRef).toEqual(SHOP_AIRP_CATALOG.ref);
  const host = f.runtime.airpGame.forSave(f.saveId, 24);
  expect((await host.host.read()).snapshot.campaign.shop?.day).toBe(1);
  await host.sync();
  expect(f.read().airpGame).not.toBeNull();
  expect(directorView(f.read())).not.toBeNull();
  for (let phase = 0; phase < 4; phase++) await f.commit({type: "advance-phase"});
  await f.commit({type: "purchase-product", shopId: "shop.mansion", productId: "product.equipment.spare-blade", day: 2, quoteVersion: 1, scheduleVersion: 1, quantity: 1});
  expect((await host.host.read()).snapshot.campaign.inventory).toHaveLength(1);
  expect(f.runtime.queries.shop(f.read())!.products).toHaveLength(6);
});
